import { StyleSheet } from 'react-native';
import { palette, typography } from '../../../shared/theme/palette';

export const home_screen_styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.cream,
  },
  screen_content: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 34,
    gap: 20,
  },
  greeting_section: {
    gap: 6,
  },
  date_text: {
    fontFamily: typography.body_medium,
    color: palette.walnut_soft,
    fontSize: 14,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  greeting_text: {
    fontFamily: typography.display,
    color: palette.walnut_deep,
    fontSize: 44,
    lineHeight: 52,
  },
  name_text: {
    fontFamily: typography.display,
    fontStyle: 'italic',
    color: palette.sky_ink,
    fontSize: 44,
    lineHeight: 52,
  },
  weather_card: {
    backgroundColor: palette.sky_deep,
    borderRadius: 22,
    borderCurve: 'continuous',
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    boxShadow: '0 8px 18px rgba(74, 126, 151, 0.25)',
  },
  weather_left: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  weather_temp_text: {
    fontFamily: typography.display,
    color: palette.walnut_deep,
    fontSize: 36,
    lineHeight: 38,
    fontVariant: ['tabular-nums'],
  },
  weather_desc_text: {
    fontFamily: typography.body,
    color: palette.walnut,
    fontSize: 15,
  },
  weather_right: {},
  weather_day_text: {
    fontFamily: typography.body_medium,
    color: palette.walnut,
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
    textAlign: 'right',
  },
  weather_hint_text: {
    fontFamily: typography.body_medium,
    color: palette.walnut_deep,
    fontSize: 17,
  },
  wardrobe_section: {
    gap: 12,
  },
  section_title: {
    fontFamily: typography.display,
    color: palette.walnut,
    fontSize: 24,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  stats_row: {
    flexDirection: 'row',
    gap: 10,
  },
  stats_card: {
    flex: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    padding: 14,
    gap: 10,
  },
  stats_card_pressed: {
    opacity: 0.84,
  },
  stats_card_header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  stats_card_title: {
    fontFamily: typography.display,
    color: palette.walnut,
    fontSize: 34,
  },
  stats_card_value: {
    fontFamily: typography.display,
    color: palette.walnut_deep,
    fontSize: 44,
    lineHeight: 44,
    fontVariant: ['tabular-nums'],
  },
  ia_card: {
    borderRadius: 24,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut_deep,
    padding: 16,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    boxShadow: '0 12px 18px rgba(74, 51, 30, 0.25)',
  },
  ia_card_left: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  ia_icon_chip: {
    backgroundColor: palette.sky,
    borderRadius: 14,
    borderCurve: 'continuous',
    height: 44,
    width: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ia_copy: {
    flex: 1,
  },
  ia_title: {
    color: palette.white,
    fontFamily: typography.display,
    fontSize: 32,
  },
  ia_subtitle: {
    color: palette.cream_deep,
    fontFamily: typography.body,
    fontSize: 14,
  },
  recent_section: {
    gap: 10,
  },
  recent_header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  recent_header_title: {
    fontFamily: typography.display,
    color: palette.walnut,
    fontSize: 20,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  recent_header_link: {
    color: palette.sky_ink,
    fontFamily: typography.body_medium,
    fontSize: 15,
  },
  recent_list_content: {
    gap: 12,
    paddingBottom: 6,
  },
  recent_item: {
    width: 122,
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    padding: 12,
    gap: 8,
  },
  recent_item_icon_container: {
    height: 58,
    borderRadius: 12,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.cream,
  },
  recent_item_name: {
    color: palette.walnut_deep,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
});