import { StyleSheet } from 'react-native';
import { palette, typography } from '../../../shared/theme/palette';

export const outfit_create_screen_styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.cream,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 40,
    gap: 18,
  },
  header_row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  header_action: {
    paddingHorizontal: 6,
    paddingVertical: 6,
    minWidth: 72,
    alignItems: 'center',
  },
  header_action_text: {
    color: palette.text_muted,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  header_title: {
    color: palette.walnut_deep,
    fontFamily: typography.display,
    fontSize: 20,
    lineHeight: 26,
  },
  section: {
    gap: 8,
  },
  section_header_row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  section_label: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 12,
    letterSpacing: 0.6,
  },
  section_hint: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 12,
  },
  input_card: {
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  input: {
    height: 40,
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 14,
  },
  chips_row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    borderRadius: 14,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.sky_deep,
    backgroundColor: palette.cream,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  chip_active: {
    borderColor: palette.walnut,
    backgroundColor: palette.walnut,
  },
  chip_text: {
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 13,
  },
  chip_text_active: {
    color: palette.white,
    fontFamily: typography.body_medium,
  },
  selected_list: {
    gap: 12,
  },
  selected_card: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 18,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    padding: 10,
  },
  selected_card_left: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  selected_image_wrap: {
    width: 54,
    height: 54,
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.cream,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  selected_image: {
    width: '100%',
    height: '100%',
  },
  selected_info: {
    flex: 1,
    gap: 2,
  },
  selected_label: {
    color: palette.text_muted,
    fontFamily: typography.body_medium,
    fontSize: 11,
    letterSpacing: 0.6,
  },
  selected_title: {
    color: palette.walnut_deep,
    fontFamily: typography.display,
    fontSize: 18,
    lineHeight: 20,
  },
  selected_meta: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 12,
  },
  selected_actions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  action_button: {
    width: 30,
    height: 30,
    borderRadius: 12,
    borderCurve: 'continuous',
    backgroundColor: palette.cream,
    alignItems: 'center',
    justifyContent: 'center',
  },
  add_card: {
    borderRadius: 20,
    borderCurve: 'continuous',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: palette.walnut_soft,
    backgroundColor: palette.cream,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  add_icon_wrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    alignItems: 'center',
    justifyContent: 'center',
  },
  add_text: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
  error_banner: {
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut_deep,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  error_text: {
    color: palette.white,
    fontFamily: typography.body,
    fontSize: 13,
  },
  submit_button: {
    minHeight: 46,
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  submit_button_disabled: {
    opacity: 0.6,
  },
  submit_button_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 15,
  },
  selector_overlay: {
    flex: 1,
    backgroundColor: 'rgba(33,24,16,0.45)',
    justifyContent: 'flex-end',
  },
  selector_sheet: {
    backgroundColor: palette.cream,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderCurve: 'continuous',
    padding: 16,
    gap: 12,
    height: '80%',
  },
  selector_header_row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selector_title: {
    color: palette.walnut_deep,
    fontFamily: typography.display,
    fontSize: 20,
  },
  selector_close: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  selector_search: {
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    paddingHorizontal: 12,
  },
  selector_search_input: {
    height: 40,
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 14,
  },
  selector_list: {
    flex: 1,
  },
  selector_list_content: {
    gap: 10,
    paddingBottom: 12,
  },
  selector_loading: {
    paddingVertical: 12,
    gap: 8,
    alignItems: 'center',
  },
  selector_loading_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 13,
  },
  selector_item: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    padding: 10,
    gap: 12,
  },
  selector_item_selected: {
    backgroundColor: palette.sky,
  },
  selector_item_left: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  selector_item_image_wrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    borderCurve: 'continuous',
    backgroundColor: palette.cream,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  selector_item_image: {
    width: '100%',
    height: '100%',
  },
  selector_item_info: {
    flex: 1,
    gap: 2,
  },
  selector_item_title: {
    color: palette.walnut_deep,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
  selector_item_subtitle: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 12,
  },
  selector_check: {
    width: 28,
    height: 28,
    borderRadius: 10,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selector_check_placeholder: {
    width: 28,
    height: 28,
    borderRadius: 10,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.walnut_soft,
  },
  selector_empty: {
    alignItems: 'center',
    paddingVertical: 18,
  },
  selector_empty_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 13,
    textAlign: 'center',
  },
});
