import { StyleSheet } from 'react-native';
import { palette, typography } from '../../../shared/theme/palette';

export const prenda_create_ia_screen_styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.cream,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 120,
    gap: 14,
  },
  back_button: {
    alignSelf: 'flex-start',
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  back_button_text: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  title: {
    color: palette.walnut_deep,
    fontFamily: typography.display,
    fontSize: 34,
    lineHeight: 38,
  },
  subtitle: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 14,
  },
  visual_card: {
    borderRadius: 24,
    borderCurve: 'continuous',
    backgroundColor: palette.white,
    height: 320,
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 10px 16px rgba(74, 51, 30, 0.14)',
    overflow: 'hidden',
  },
  visual_image: {
    width: '100%',
    height: '100%',
  },
  visual_placeholder_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 18,
  },
  photo_actions_row: {
    flexDirection: 'row',
    gap: 8,
  },
  photo_action_button: {
    flex: 1,
    minHeight: 42,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  photo_action_button_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
  photo_action_button_secondary: {
    minWidth: 84,
    minHeight: 42,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  photo_action_button_secondary_text: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
  card: {
    borderRadius: 18,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    padding: 12,
    gap: 10,
  },
  helper_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 12,
    lineHeight: 17,
  },
  error_banner: {
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut_deep,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  error_text: {
    color: palette.white,
    fontFamily: typography.body,
    fontSize: 13,
  },
  submit_button: {
    minHeight: 46,
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  submit_button_disabled: {
    opacity: 0.6,
  },
  submit_button_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 15,
  },
  loading_state: {
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    paddingVertical: 16,
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loading_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 13,
  },
});