import { StyleSheet } from 'react-native';
import { palette, typography } from '../../../shared/theme/palette';

export const prenda_create_manual_screen_styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.cream,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 120,
    gap: 14,
  },
  back_button: {
    alignSelf: 'flex-start',
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  back_button_text: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  title: {
    color: palette.walnut_deep,
    fontFamily: typography.display,
    fontSize: 34,
    lineHeight: 38,
  },
  subtitle: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 14,
  },
  visual_card: {
    borderRadius: 24,
    borderCurve: 'continuous',
    backgroundColor: palette.white,
    height: 300,
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 10px 16px rgba(74, 51, 30, 0.14)',
    overflow: 'hidden',
  },
  visual_image: {
    width: '100%',
    height: '100%',
  },
  visual_placeholder_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 14,
  },
  photo_actions_row: {
    flexDirection: 'row',
    gap: 8,
  },
  photo_action_button: {
    flex: 1,
    minHeight: 42,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  photo_action_button_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
  photo_action_button_secondary: {
    minWidth: 84,
    minHeight: 42,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  photo_action_button_secondary_text: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
  card: {
    borderRadius: 18,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    padding: 12,
    gap: 10,
  },
  field_label: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  input: {
    height: 42,
    borderRadius: 14,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.sky_deep,
    backgroundColor: palette.cream,
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 14,
    paddingHorizontal: 12,
  },
  select_trigger: {
    minHeight: 42,
    borderRadius: 14,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.sky_deep,
    backgroundColor: palette.cream,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  select_trigger_text: {
    flex: 1,
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 14,
  },
  select_dropdown: {
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream,
    borderWidth: 1,
    borderColor: palette.sky_deep,
    overflow: 'hidden',
  },
  select_option: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  select_option_active: {
    backgroundColor: palette.walnut,
  },
  select_option_text: {
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 13,
  },
  select_option_text_active: {
    color: palette.white,
    fontFamily: typography.body_medium,
  },
  color_input_row: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  color_input_wrap: {
    flex: 1,
    borderRadius: 14,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.sky_deep,
    backgroundColor: palette.cream,
    paddingHorizontal: 12,
  },
  color_input: {
    height: 42,
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 14,
  },
  color_add_button: {
    minHeight: 42,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  color_add_button_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  suggestions_wrap: {
    borderRadius: 14,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.sky_deep,
    backgroundColor: palette.cream,
    overflow: 'hidden',
  },
  suggestion_item: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.cream_deep,
  },
  suggestion_item_text: {
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 13,
  },
  chips_wrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    borderRadius: 14,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.sky_deep,
    backgroundColor: palette.cream,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  chip_active: {
    borderColor: palette.walnut,
    backgroundColor: palette.walnut,
  },
  chip_text: {
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 13,
  },
  chip_text_active: {
    color: palette.white,
    fontFamily: typography.body_medium,
  },
  selected_color_chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    paddingLeft: 12,
    paddingRight: 6,
    paddingVertical: 7,
  },
  selected_color_chip_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  selected_color_chip_remove_button: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  helper_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 12,
  },
  error_banner: {
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut_deep,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  error_text: {
    color: palette.white,
    fontFamily: typography.body,
    fontSize: 13,
  },
  submit_button: {
    minHeight: 46,
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  submit_button_disabled: {
    opacity: 0.6,
  },
  submit_button_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 15,
  },
  loading_state: {
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    paddingVertical: 16,
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loading_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 13,
  },
});