import { StyleSheet } from 'react-native';
import { palette, typography } from '../../../shared/theme/palette';

export const search_input_placeholder_color = palette.text_muted;

export const prendas_screen_styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.cream,
  },
  list_content: {
    paddingHorizontal: 18,
  },
  header_stack: {
    gap: 12,
    paddingTop: 10,
    paddingBottom: 14,
  },
  screen_title: {
    textAlign: 'center',
    color: palette.walnut_deep,
    fontFamily: typography.display,
    fontSize: 41,
    lineHeight: 46,
  },
  controls_row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  search_box: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
    gap: 8,
  },
  search_input: {
    flex: 1,
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 15,
  },
  icon_action_button: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon_action_button_active: {
    backgroundColor: palette.walnut,
  },
  add_button: {
    height: 44,
    paddingHorizontal: 16,
    borderRadius: 22,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    alignItems: 'center',
    justifyContent: 'center',
  },
  add_button_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 15,
  },
  filters_scroll_content: {
    gap: 8,
    paddingBottom: 2,
  },
  filter_card: {
    borderRadius: 20,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    padding: 12,
    gap: 12,
    boxShadow: '0 8px 14px rgba(74, 51, 30, 0.12)',
  },
  filter_section: {
    gap: 8,
  },
  filter_label: {
    color: palette.walnut_deep,
    fontFamily: typography.body_medium,
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  filter_header_row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  filter_value: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 12,
  },
  level_row: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
    marginBottom: 6,
  },
  level_pill: {
    flex: 1,
    height: 20,
    borderRadius: 10,
    borderCurve: 'continuous',
    // Usamos el fondo claro porque el contenedor de filtros ya es oscuro
    backgroundColor: palette.cream, 
  },
  level_pill_active_elegance: {
    backgroundColor: palette.walnut,
  },
  level_pill_active_warmth: {
    backgroundColor: palette.sky_ink,
  },
  filter_choice_row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 6,
  },
  filter_choice_chip: {
    borderRadius: 14,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.sky_deep,
    backgroundColor: palette.cream,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  filter_choice_chip_active: {
    borderColor: palette.walnut,
    backgroundColor: palette.walnut,
  },
  filter_choice_chip_text: {
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 13,
  },
  filter_choice_chip_text_active: {
    color: palette.white,
    fontFamily: typography.body_medium,
  },
  filter_text_input_wrap: {
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream,
    borderWidth: 1,
    borderColor: palette.sky_deep,
    paddingHorizontal: 12,
  },
  filter_text_input: {
    height: 40,
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 14,
  },
  filter_actions_row: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  filter_action_button_secondary: {
    borderRadius: 12,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.walnut_soft,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.cream,
  },
  filter_action_button_secondary_text: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  filter_action_button_primary: {
    borderRadius: 12,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filter_action_button_primary_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  filter_chip: {
    borderRadius: 16,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.cream_deep,
    backgroundColor: palette.cream,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  filter_chip_active: {
    borderColor: palette.walnut,
    backgroundColor: palette.walnut,
  },
  filter_chip_text: {
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 14,
  },
  filter_chip_text_active: {
    color: palette.white,
    fontFamily: typography.body_medium,
  },
  results_caption: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 13,
  },
  list_column: {
    gap: 12,
    marginBottom: 14,
  },
  card_wrapper: {
    flex: 1,
    minWidth: 0,
  },
  card_wrapper_single_last: {
    flex: 0,
    width: '49%',
  },
  loading_state: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loading_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 15,
  },
  empty_state: {
    borderRadius: 18,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    paddingVertical: 18,
    paddingHorizontal: 14,
    gap: 8,
    marginTop: 6,
  },
  empty_title: {
    color: palette.walnut_deep,
    fontFamily: typography.display,
    fontSize: 26,
    lineHeight: 30,
  },
  empty_subtitle: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 14,
  },
  retry_button: {
    alignSelf: 'flex-start',
    marginTop: 2,
    borderRadius: 15,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  retry_button_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  inline_error_banner: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 84,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut_deep,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inline_error_text: {
    color: palette.white,
    fontFamily: typography.body,
    fontSize: 13,
  },
  add_options_overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
  },
  add_options_backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  add_options_card: {
    marginHorizontal: 12,
    borderRadius: 18,
    borderCurve: 'continuous',
    backgroundColor: palette.cream,
    padding: 12,
    gap: 10,
    boxShadow: '0 8px 14px rgba(74, 51, 30, 0.2)',
  },
  add_options_title: {
    color: palette.walnut_deep,
    fontFamily: typography.body_medium,
    fontSize: 16,
    marginBottom: 4,
  },
  add_options_button_primary: {
    minHeight: 42,
    borderRadius: 50,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.walnut,
  },
  add_options_button_primary_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
  add_options_button_disabled: {
    minHeight: 42,
    borderRadius: 50,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.cream_deep,
    borderWidth: 1,
    borderColor: palette.sky_deep,
  },
  add_options_button_ia: {
    minHeight: 42,
    borderRadius: 50,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.sky,
    flexDirection: 'row',
    gap: 9,
  },
  add_options_button_disabled_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 14,
  },
  add_options_button_secondary: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  add_options_button_secondary_text: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
  add_options_button_ia_text: {
    color: palette.walnut_deep,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
});
