import { StyleSheet } from 'react-native';
import { palette, typography } from '../../../shared/theme/palette';

export const prenda_create_manual_screen_styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.cream,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 40,
    gap: 18,
  },
  header_row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  header_action: {
    paddingHorizontal: 6,
    paddingVertical: 6,
    minWidth: 72,
    alignItems: 'center',
  },
  header_action_text: {
    color: palette.text_muted,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  header_action_text_primary: {
    color: palette.sky_ink,
  },
  header_action_text_disabled: {
    opacity: 0.6,
  },
  header_title: {
    color: palette.walnut_deep,
    fontFamily: typography.display,
    fontSize: 20,
    lineHeight: 26,
  },
  photo_card: {
    borderRadius: 24,
    borderCurve: 'continuous',
    backgroundColor: palette.sky,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: '#BFD6E2',
    borderStyle: 'dashed',
  },
  photo_image: {
    width: '100%',
    borderRadius: 18,
  },
  photo_placeholder: {
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  photo_icon_wrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photo_placeholder_text: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 14,
  },
  photo_actions_row: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
  },
  photo_action_button: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.cream,
    borderRadius: 14,
    borderCurve: 'continuous',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#D9C9B5',
  },
  photo_action_button_text: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 13,
  },
  photo_clear_button: {
    alignSelf: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  photo_clear_button_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 12,
  },
  section: {
    gap: 8,
  },
  section_label: {
    color: palette.walnut,
    fontFamily: typography.body_medium,
    fontSize: 12,
    letterSpacing: 0.6,
  },
  section_header_row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  section_hint: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 12,
  },
  input_card: {
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  input: {
    height: 40,
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 14,
  },
  type_grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  helper_box: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  helper_icon: {
    marginTop: 2,
  },
  helper_text: {
    flex: 1,
    flexShrink: 1,
    color: palette.text_primary,
    fontFamily: typography.body,
    fontSize: 15,
    lineHeight: 17,
    textAlign: 'justify',
  },
  type_card: {
    width: '31%',
    height: 86,
    minWidth: 90,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  type_card_active: {
    backgroundColor: palette.walnut,
  },
  type_label: {
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 12,
    textAlign: 'center',
    marginTop: 6,
  },
  type_label_active: {
    color: palette.white,
    fontFamily: typography.body_medium,
  },
  custom_type_input_wrap: {
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  level_row: {
    flexDirection: 'row',
    gap: 8,
  },
  level_pill: {
    flex: 1,
    height: 30,
    borderRadius: 10,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
  },
  level_pill_active: {
    backgroundColor: palette.walnut,
  },
  level_pill_active_warmth: {
    backgroundColor: palette.sky_ink,
  },
  colors_card: {
    borderRadius: 18,
    borderCurve: 'continuous',
    backgroundColor: palette.cream_deep,
    padding: 12,
    gap: 12,
  },
  colors_grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  color_item: {
    alignItems: 'center',
    gap: 6,
    width: '22%',
  },
  color_swatch: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  color_swatch_selected: {
    borderColor: palette.walnut,
  },
  color_label: {
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 11,
    textAlign: 'center',
  },
  type_icon: {
    marginBottom: 6,
  },
  custom_color_button: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'center',
    paddingVertical: 6,
  },
  custom_color_button_text: {
    color: palette.sky_ink,
    fontFamily: typography.body_medium,
    fontSize: 12,
  },
  color_input_row: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  color_input_wrap: {
    flex: 1,
    borderRadius: 14,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: '#D9C9B5',
    backgroundColor: palette.cream,
    paddingHorizontal: 12,
  },
  color_input: {
    height: 40,
    color: palette.walnut,
    fontFamily: typography.body,
    fontSize: 13,
  },
  color_add_button: {
    minHeight: 40,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  color_add_button_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 12,
  },
  chips_wrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  selected_color_chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    paddingLeft: 12,
    paddingRight: 6,
    paddingVertical: 7,
  },
  selected_color_chip_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 12,
  },
  selected_color_chip_remove_button: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  error_banner: {
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut_deep,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  error_text: {
    color: palette.white,
    fontFamily: typography.body,
    fontSize: 13,
  },
  submit_button: {
    minHeight: 50,
    borderRadius: 50,
    borderCurve: 'continuous',
    backgroundColor: palette.walnut,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    boxShadow: '0 12px 18px rgba(74, 51, 30, 0.2)',
  },
  submit_button_disabled: {
    opacity: 0.6,
  },
  submit_button_text: {
    color: palette.white,
    fontFamily: typography.body_medium,
    fontSize: 15,
  },
  loading_state: {
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.cream,
    paddingVertical: 10,
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loading_text: {
    color: palette.text_muted,
    fontFamily: typography.body,
    fontSize: 12,
  },
});